// URL consistency: /privacypolicy → /politique-confidentialite (French slug).
// React-side <Navigate replace> handles the client redirect. For SEO, the VPS
// nginx config should also send a hard 301:
//
//   rewrite ^/privacypolicy$ /politique-confidentialite permanent;
//
// (or in an Apache .htaccess: Redirect 301 /privacypolicy /politique-confidentialite)

import type { RouteRecord } from "vite-react-ssg";
import { Navigate } from "react-router";
import App from "./App";
import ProtectedRoute from "./middleware/ProtectedRoute";
import { blogPosts } from "./data/blogPosts";

// Eager imports for PRERENDERED public routes.
// These routes are statically generated by vite-react-ssg (each carries an
// `entry:` field). Lazy-importing them caused a hydration duplication bug:
// React Router suspended on the lazy() during client hydration, rendered no
// HydrateFallback, then mounted the Component fresh once the chunk resolved —
// leaving the SSR'd DOM orphaned and visually duplicated. Console showed:
//   "No HydrateFallback element provided to render during initial hydration"
//   "Cannot read properties of undefined (reading '0')"
// Fix: ship these as eager Component imports so hydration is synchronous.
// Non-prerendered (SPA-only) and role-gated routes stay lazy below.
import Home from "@pages/generales/Home";
import APropos from "@pages/generales/APropos";
import Service from "@pages/generales/Service";
import Tarif from "@pages/generales/Tarif";
import Contact from "@pages/generales/Contact";
import Ressources from "@pages/generales/Ressources";
import Politique from "@pages/generales/Politique";
import Condition from "@pages/generales/Condition";
import Maintenance from "@pages/generales/Maintenance";
import Details from "@pages/generales/Details";
import Details1 from "@pages/generales/Details1";
import Details2 from "@pages/generales/Details2";
import Details3 from "@pages/generales/Details3";
import Details4 from "@pages/generales/Details4";
import Details5 from "@pages/generales/Details5";
import Details6 from "@pages/generales/Details6";
import Details7 from "@pages/generales/Details7";
import EquipeArike from "@pages/generales/EquipeArike";
import BlogIndex from "@pages/generales/BlogIndex";
import BlogArticle from "@pages/generales/BlogArticle";

// Helper: wrap default-export pages so vite-react-ssg's lazy() gets { Component }.
const lazyDefault =
  <T extends { default: React.ComponentType<unknown> }>(loader: () => Promise<T>) =>
  async () => {
    const mod = await loader();
    return { Component: mod.default };
  };

export const routes: RouteRecord[] = [
  {
    path: "/",
    Component: App,
    entry: "src/App.tsx",
    children: [
      // ── Public pages (prerendered) ──────────────────────────────────────
      { index: true, Component: Home, entry: "src/pages/generales/Home.tsx" },
      { path: "a-propos", Component: APropos, entry: "src/pages/generales/APropos.tsx" },
      { path: "services", Component: Service, entry: "src/pages/generales/Service.tsx" },
      { path: "tarifs", Component: Tarif, entry: "src/pages/generales/Tarif.tsx" },
      { path: "contact", Component: Contact, entry: "src/pages/generales/Contact.tsx" },
      { path: "ressources", Component: Ressources, entry: "src/pages/generales/Ressources.tsx" },
      { path: "politique-confidentialite", Component: Politique, entry: "src/pages/generales/Politique.tsx" },
      // Client-side redirect for the legacy English slug. Server-side 301 should
      // be added at the nginx layer (see top of file).
      { path: "privacypolicy", element: <Navigate to="/politique-confidentialite" replace /> },
      { path: "cgu", Component: Condition, entry: "src/pages/generales/Condition.tsx" },
      { path: "maintenance", Component: Maintenance, entry: "src/pages/generales/Maintenance.tsx" },

      // Marketing "Details" pages (prerendered)
      { path: "location", Component: Details, entry: "src/pages/generales/Details.tsx" },
      { path: "conduite", Component: Details1, entry: "src/pages/generales/Details1.tsx" },
      { path: "actualisation", Component: Details2, entry: "src/pages/generales/Details2.tsx" },
      { path: "fabrication-permis", Component: Details3, entry: "src/pages/generales/Details3.tsx" },
      { path: "passerelle", Component: Details4, entry: "src/pages/generales/Details4.tsx" },
      { path: "code-en-ligne", Component: Details5, entry: "src/pages/generales/Details5.tsx" },
      { path: "accompagnement", Component: Details6, entry: "src/pages/generales/Details6.tsx" },
      { path: "post-permis", Component: Details7, entry: "src/pages/generales/Details7.tsx" },

      // E-E-A-T author page (prerendered for SEO)
      { path: "equipe/arike", Component: EquipeArike, entry: "src/pages/generales/EquipeArike.tsx" },

      // Blog (prerendered: index + every article)
      { path: "blog", Component: BlogIndex, entry: "src/pages/generales/BlogIndex.tsx" },
      {
        path: "blog/:slug",
        Component: BlogArticle,
        entry: "src/pages/generales/BlogArticle.tsx",
        getStaticPaths: () => blogPosts.map((p) => `blog/${p.slug}`),
      },

      // Quiz (public, client-rendered)
      { path: "quiz", lazy: lazyDefault(() => import("@pages/generales/Quiz")) },

      // ── SPA-only routes (not prerendered) ───────────────────────────────
      { path: "connexion/:token?", lazy: lazyDefault(() => import("@pages/auth/LoginPage")) },
      { path: "inscription", lazy: lazyDefault(() => import("@pages/auth/RegisterPage")) },
      { path: "reset-password", lazy: lazyDefault(() => import("@pages/auth/reset-password/ResetPasswordPage")) },

      // Learners
      {
        Component: ProtectedRoute,
        children: [
          {
            path: "learners",
            lazy: lazyDefault(() => import("@components/learners/ApprenantLayout")),
            children: [
              { index: true, lazy: lazyDefault(() => import("@pages/learners/dashboard/Dashboard")) },
              { path: "dashboard", lazy: lazyDefault(() => import("@pages/learners/dashboard/Dashboard")) },
              { path: "code", lazy: lazyDefault(() => import("@pages/learners/code/Code")) },
              { path: "conduite", lazy: lazyDefault(() => import("@pages/learners/conduite/Conduite")) },
              { path: "examens", lazy: lazyDefault(() => import("@pages/learners/examens/Examens")) },
              { path: "boutique", lazy: lazyDefault(() => import("@pages/learners/boutique/Boutique")) },
              { path: "parametres", lazy: lazyDefault(() => import("@/components/learners/Parametres/Parametres")) },
              { path: "reservercours", lazy: lazyDefault(() => import("@pages/learners/ReserverLecon")) },
              {
                path: "quiz/history",
                lazy: async () => ({ Component: (await import("@pages/learners/Quiz")).QuizHistory }),
              },
            ],
          },
        ],
      },

      // Monitor
      {
        Component: ProtectedRoute,
        children: [
          {
            path: "monitor",
            lazy: lazyDefault(() => import("./layout/MonitorLayout")),
            children: [
              { index: true, lazy: lazyDefault(() => import("@pages/moniteur/Dashboard")) },
              { path: "dashboard", lazy: lazyDefault(() => import("@pages/moniteur/Dashboard")) },
              { path: "planning", lazy: lazyDefault(() => import("@pages/moniteur/Planing")) },
              { path: "apprenants", lazy: lazyDefault(() => import("@pages/moniteur/Apprenants")) },
              { path: "assistance", lazy: lazyDefault(() => import("@pages/moniteur/Assistance")) },
              { path: "parametres", lazy: lazyDefault(() => import("@pages/moniteur/Settings")) },
              { path: "paiement", lazy: lazyDefault(() => import("@pages/moniteur/Paiement")) },
              { path: "transactions", lazy: lazyDefault(() => import("@components/moniteurs/TransactionHistory")) },
              { path: "rendez-vous", lazy: lazyDefault(() => import("./pages/moniteur/RendezVous")) },
              { path: "examen", lazy: lazyDefault(() => import("@pages/moniteur/MonitorExamen")) },
            ],
          },
        ],
      },

      // Admin
      {
        Component: ProtectedRoute,
        children: [
          {
            path: "admin",
            lazy: lazyDefault(() => import("./layout/AdminLayout")),
            children: [
              { index: true, lazy: lazyDefault(() => import("@pages/admin/Dashboard")) },
              { path: "dashboard", lazy: lazyDefault(() => import("@pages/admin/Dashboard")) },
              { path: "moniteurs", lazy: lazyDefault(() => import("./pages/admin/Monitor")) },
              { path: "moniteurs/learners", lazy: lazyDefault(() => import("./pages/admin/MonitorLeanerListe")) },
              { path: "paiement", lazy: lazyDefault(() => import("./pages/admin/Paiement")) },
              { path: "moniteurs/rendez-vous", lazy: lazyDefault(() => import("./pages/admin/MonitorApointementListe")) },
              { path: "moniteurs/planning", lazy: lazyDefault(() => import("./pages/admin/MonitorAvalibilities")) },
              { path: "moniteurs/details", lazy: lazyDefault(() => import("./components/admin/MonitorShow")) },
              { path: "parametres", lazy: lazyDefault(() => import("./pages/admin/Settings")) },
              { path: "administrateurs", lazy: lazyDefault(() => import("./pages/admin/Administrateur")) },
              { path: "apprenants", lazy: lazyDefault(() => import("./pages/admin/Learners/ListLearners")) },
              { path: "apprenants/:id", lazy: lazyDefault(() => import("@pages/admin/Learners/ApprenantDetailsPage")) },
              { path: "services", lazy: lazyDefault(() => import("./pages/admin/services/Service")) },
              { path: "code-de-la-route", lazy: lazyDefault(() => import("./pages/admin/CodeRoute")) },
              { path: "examen", lazy: lazyDefault(() => import("./pages/admin/Examen")) },
            ],
          },
        ],
      },

      {
        path: "modale",
        lazy: async () => {
          const Mod = (await import("@components/moniteurs/PlanningComponent")).default;
          return {
            Component: () => (
              <Mod setIsOpenPlanningModal={() => {}} isOpenPlanningModal={false} />
            ),
          };
        },
      },
      { path: "payment-success", lazy: lazyDefault(() => import("./pages/payment/PaymentSucccess")) },

      // Public Quiz Routes
      { path: "learners/quiz", element: <Navigate to="/quiz" replace /> },
      {
        path: "quiz/:categoryCode",
        lazy: async () => ({ Component: (await import("@pages/learners/Quiz")).QuizPage }),
      },
      {
        path: "quiz/results/:attemptId",
        lazy: async () => ({ Component: (await import("@pages/learners/Quiz")).QuizResults }),
      },

      { path: "*", lazy: lazyDefault(() => import("@pages/generales/NotFound")) },
    ],
  },
];
